### ISSUE TITLE
Allow addons to add commands to mr.developer

### ISSUE THREAD

**Issue by fschulze** [fschulze/mr.developer#109]
Currently this is just a reminder to myself. If anyone cares to comment on possible ways (I was thinking entry-points), please go ahead!

**Comment by gforcada** [comment]
Since mr.developer 1.32 this seems to be possible via entry points, so I guess this could be closed, right?

**Comment by fschulze** [comment]
Yes, btw, the py.test plugin implementation is now available via https://pypi.python.org/pypi/pluggy, though the API might still change.
