### ISSUE TITLE
Version unpinning does not take in to account the safe_name

### ISSUE THREAD

**Issue by ale-rt** [fschulze/mr.developer#149]
Packages like pkg.foo_bar are pinned as pkg.foo-bar.
Generally speaking all the characters not matching [^A-Za-z0-9.] are replaced by a dash.

mr.developer does not take this into account.

I have a (simple) patch ready:
- https://github.com/ale-rt/mr.developer/commit/30d5683368581a5e6253e93560e23f742adba13f

I also added a test but it is failing, mainly because I don't know how to specify in the mock the sources correctly to enter here:
- https://github.com/ale-rt/mr.developer/commit/30d5683368581a5e6253e93560e23f742adba13f#diff-ca714ba2a8cd5a11483d9f5edf7a4a66R181

If I can get this test working I will submit a pull request.

Thanks for the work you did.

**Comment by ale-rt** [comment]
I updated the PR rebasing on today master.
Any chance of getting this merged?

**Comment by reinout** [comment]
The PR has been merged, so the issue can be closed, I think.

**Comment by ale-rt** [comment]
Closed by #150
