### ISSUE TITLE
git submodules update uses submodule name instead of path

### ISSUE THREAD

**Issue by thet** [fschulze/mr.developer#160]
i have a git submodule, which `.gitmodules` contents the following:

```
[submodule "mockup"]
    path = plone/mockup
    url = git://github.com/plone/mockup.git
```

`mr.developer.git.GitWorkingCopy.git_init_submodules` returns the names of the initialized submodules. `mr.developer.git.GitWorkingCopy.git_update_submodules` uses these names to run `git submodule update mockup` instead of the path like so: `git submodule update plone/mockup`.
this does not work and a `git submodule update mockup` error is raised.

we can get the path via the output of `git submodule status`.

**Comment by navytux** [comment]
I have deiscovered the same issue regarding mr.deceloper vs git submodules.
My submodule name is "ccan" and path is "3rdparty/ccan":

---- 8< ---- (https://lab.nexedi.cn/kirr/wendelin.core/blob/master/.gitmodules)
[submodule "ccan"]
	path = 3rdparty/ccan
	url = git://git.ozlabs.org/~ccan/ccan
---- 8< ----

This .gitmodules was created automatically via `git submodule add` command, so it's not a "user configuration error".

Basically there is a difference between submodule "name" (ccan) and submodule "path" (3rdparty/ccan). Currently mr.developers uses submodule name where path should be used, and that leads to inability to intialize checkout:

---- 8< ----
$ cat buildout.cfg 
[buildout]
parts = wendelin.core
extensions = mr.developer
auto-checkout = wendelin.core

[wendelin.core]
recipe = zc.recipe.egg:custom

[sources]
wendelin.core = git https://lab.nexedi.cn/kirr/wendelin.core.git


$ ./bin/buildout 
Getting distribution for 'mr.developer'.
Got mr.developer 1.31.
mr.developer: Creating missing sources dir /home/kirr/t/w8/src.
mr.developer: Queued 'wendelin.core' for checkout.
mr.developer: Cloned 'wendelin.core' with git.
mr.developer: git submodule update failed.
mr.developer: 
mr.developer: There have been errors, see messages above.
---- 8< ----

Here is the trace of git commands mr.developer runs (obatined with patch [1]):

---- 8< ----
$ ./bin/buildout 
mr.developer: Queued 'wendelin.core' for checkout.
run_git ['clone', '--quiet', 'https://lab.nexedi.cn/kirr/wendelin.core.git', '/home/kirr/t/w7/src/wendelin.core'] {}
run_git ['submodule', 'init'] {'cwd': '/home/kirr/t/w7/src/wendelin.core'}
initialized_submodules: ['ccan']

stdout Submodule 'ccan' (git://git.ozlabs.org/~ccan/ccan) registered for path '3rdparty/ccan'

stderr 

submodule ccan
run_git ['submodule', 'update', 'ccan'] {'cwd': '/home/kirr/t/w7/src/wendelin.core'}    # <- NOTE here (1)
mr.developer: Cloned 'wendelin.core' with git.
mr.developer: git submodule update failed.
mr.developer: 
mr.developer: There have been errors, see messages above.
---- 8< ----

(1) it should be `git submodule update 3rdparty/ccan`

Thanks beforehand for fixing this,
Kirill

[1]
diff -up ./mr/developer/git.py.kirr ./mr/developer/git.py
--- ./mr/developer/git.py.kirr  2015-05-01 15:06:32.000000000 +0300
+++ ./mr/developer/git.py       2015-05-01 15:20:44.108948582 +0300
@@ -91,6 +91,7 @@ class GitWorkingCopy(common.BaseWorkingC
             return 'remotes/%s' % self._upstream_name
 
     def run_git(self, commands, **kwargs):
+        print 'run_git', commands, kwargs
         commands.insert(0, self.git_executable)
         kwargs['stdout'] = subprocess.PIPE
         kwargs['stderr'] = subprocess.PIPE
@@ -135,9 +136,15 @@ class GitWorkingCopy(common.BaseWorkingC
             stdout, stderr, initialized = self.git_init_submodules(stdout, stderr)
             # Update only new submodules that we just registered. this is for safety reasons
             # as git submodule update on modified subomdules may cause code loss
+            print
+            print 'stdout', stdout
+            print 'stderr', stderr
             for submodule in initialized:
+                print
+                print 'submodule', submodule
                 stdout, stderr = self.git_update_submodules(stdout, stderr, submodule=submodule)
                 self.output((logger.info, "Initialized '%s' submodule at '%s' with git." % (name, submodule)))
+                print "Initialized '%s' submodule at '%s' with git." % (name, submodule)
 
         if kwargs.get('verbose', False):
             return stdout
@@ -281,6 +288,7 @@ class GitWorkingCopy(common.BaseWorkingC
         initialized_submodules = re.findall(
             r'\s+[\'"](.*?)[\'"]\s+\(.+\)',
             s(stdout))
+        print 'initialized_submodules:', initialized_submodules
         return (stdout_in + stdout, stderr_in + stderr, initialized_submodules)
 
     def git_update_submodules(self, stdout_in, stderr_in, submodule='all'):

**Comment by thet** [comment]
Closing stale issue.
