### ISSUE TITLE
Git: Switching from rev= to branch= fails

### ISSUE THREAD

**Issue by cutz** [fschulze/mr.developer#162]
Occasionally we have the need to point an environment at a specific tag/sha of a git project.

`git <url> rev=alpha/2015-04-20/001`

After testing completes we wish to go back to tracking a branch

`git <url> branch=develop`

When doing this. the mr.developer update fails with the following error:

    mr.developer: Updated 'nti.web.mobile' with git.
    mr.developer: git pull of 'nti.web.mobile' failed.
    mr.developer: From <url>
    mr.developer:    31df7e8..d076801  develop    -> origin/develop
    mr.developer: You are not currently on a branch. Please specify which
    mr.developer: branch you want to merge with. See git-pull(1) for details.

It is worth noting that transitioning from branch to rev works fine.

**Comment by mauritsvanrees** [comment]
Fixed on master.
