### ISSUE TITLE
Shallow clones?

### ISSUE THREAD

**Issue by gforcada** [fschulze/mr.developer#163]
It would be great to have this option and to disable/enable it globally (to not clutter all sources.cfg).

The main benefit of this would be to improve git cloning time on jenkins.plone.org as every single job wipes its workspace and starts from an empty folder for every job.

Would that be possible?

**Comment by fschulze** [comment]
Could you give more details on how that would work? Usage examples, links to repositories and commands you expect to be run?

**Comment by gforcada** [comment]
Basically all is about adding ``--depth=1`` on each git clone command, see git clone documentation: http://git-scm.com/docs/git-clone

The biggest upside is this:

```
git clone https://github.com/plone/buildout.coredev.git test-full
du -sh test-full
36M	test-full

git clone https://github.com/plone/buildout.coredev.git --depth=1 test-shallow
du -sh test-shallow
1,5M	test-shallow
```
A **24x saving**.

That's also what github.com/plone/papyrus (the documentation build system for docs.plone.org) is using to speed up clones.

I'm not expecting *anyone* but Jenkins and or automated tools to benefit from this, but the bandwidth savings from it would be huge for jenkins.plone.org/travis and so on.

I would expect an option like ``clone-depth=1`` which doubles as being the option to turn on the ``--depth`` argument and also can be used to specify another value rather than 1, if, for whichever reason one wants not 1 level of deepness but instead 10 or 20...

Wording is of course up to discussion, I am no native English speaker.

**Comment by fschulze** [comment]
Ahhh, I confused "shallow" with a subtree checkout. This is a very useful addition. Per repository ``depth`` is fine in IMO. For a global option I would suggest ``git-clone-depth``. If you think you can work on it yourself, look for ``newest_tag`` on how you could implement the ``depth`` option. For the global option ``update-git-submodules`` might be a model, though I looked at it briefly and it may be to complex as an example. I will gladly review and help with a PR, I don't know when I would have time to fully implement it myself though.

**Comment by gforcada** [comment]
@fschulze I hacked a possible approach on this issue on #164, could you give it a try? Is totally untested... pointers for that would be welcome :)
