### ISSUE TITLE
Git Verbose logs for mr.developer auto-checkout through buildout

### ISSUE THREAD

**Issue by tarunactivity** [fschulze/mr.developer#178]
Hi,
We are using mr.developer 1.25 and zc.buildout 2.2.1 with Github . 
I am facing issues with auto-checkout taking significantly long / even hanging , and want to enable GIT_TRACE and SSH debug statements. 

Is there a way to enable mr.developer to supply verbose logs/debug messages when used from buildout?
Buildout supports verbose logs using -vvv , but this does not seem to print logs from SSH/Git .

**Comment by fschulze** [comment]
Not out of the box. You would have to edit ``git.py`` to add that. Maybe for debugging that's already enough to do temporarily.

See https://github.com/fschulze/mr.developer#lockups-during-checkouts-and-updates for a possible reason.

**Comment by mauritsvanrees** [comment]
I have just documented another possible reason: persistent ssh connections. See commit d3615c4193323bf086c24c1f691575126dccc87d.

**Comment by mauritsvanrees** [comment]
I think this is fixed by pull request #185 which I have just released as version 1.36.
