### ISSUE TITLE
What is the best way to run a command after a repository was just checked out?

### ISSUE THREAD

**Issue by idgserpro** [fschulze/mr.developer#191]
I want to run `python bootstrap.py` and `bin/buildout` after a package in my `[sources]` buildout section is checked out. What is the best way to do it?

@hvelarde this will be useful for new packages [using sc.recipe.staticresources](https://community.plone.org/t/ann-sc-recipe-staticresources-1-0a1/5230), such as brasil.gov.agenda, that are being checked out using mr.developer. When using mr.developer with these packages, running `bin/buildout` is needed to put the js and css resources in the static folder, otherwise we get an "error 404" when trying to get these resources from the site url, so it would be nice to automate this.

**Comment by hvelarde** [comment]
what about using [Git Hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks)? cc @rodfersou

**Comment by idgserpro** [comment]
I thought about using https://pypi.python.org/pypi/plone.recipe.command in a *hacky* manner in my `buildout.cfg`, but want this to be the last resort if it's possible to do it only using mr.developer.

**Comment by idgserpro** [comment]
I've decided to go with the plone.recipe.command approach, is not that complicated. I'm using a `development.cfg` and assuming you're using the default config of mr.developer (the `git checkout` command clones the repository in `src`). You may need to adapt the commands used here (specially if you're using requirements.txt instead of bootstrap.py, if you use virtualenv, etc):

```cfg
[buildout]
extends =
    buildout.cfg

extensions +=
    mr.developer

always-checkout = force

auto-checkout =
    brasil.gov.agenda
    brasil.gov.tiles

parts +=
    bootstrap_buildout

[instance]
eggs +=
    brasil.gov.agenda
    brasil.gov.tiles

zcml +=
    brasil.gov.agenda
    brasil.gov.tiles

[sources]
brasil.gov.agenda = git git@github.com:plonegovbr/brasil.gov.agenda.git
brasil.gov.tiles = git git@github.com:plonegovbr/brasil.gov.tiles.git

[bootstrap_buildout]
recipe = plone.recipe.command
stop-on-error = yes
command =
    for i in $(bin/develop list); do
        cd "${buildout:directory}/src/$i" && "$HOME/.pythons/idg/python" bootstrap.py && bin/buildout && cd "${buildout:directory}"
    done
update-command = ${:command}
```

If you don't want to have code in your cfg files likes this or have really complex workflows, you can create a script and use it like explained in https://stackoverflow.com/a/16403628. If you need to use another shell (plone.recipe.command uses bin/sh) use https://pypi.python.org/pypi/zsft.recipe.cmd.

**Comment by hvelarde** [comment]
in fact you don't need that; this is the right way to do it:

```ini
[buildout]
...
parts +=
    ...
    node
    staticresources-brasilgovtemas
    staticresources-brasilgovagenda

[node]
recipe = gp.recipe.node
version = 6.6.0
npms = npm yarn
scripts = npm yarn

[staticresources-brasilgovtemas]
recipe = sc.recipe.staticresources
name = brasil.gov.temas
short_name = brasilgovtemas
directory = src/brasil.gov.temas/webpack

[staticresources-brasilgovagenda]
recipe = sc.recipe.staticresources
name = brasil.gov.agenda
short_name = brasilgovagenda
directory = src/brasil.gov.agenda/webpack
```

that will create the static resources at buildout time for all dependencies.

**Comment by idgserpro** [comment]
I prefer my approach: all of the packages that need to compile the static resources already have these configurations in their buildouts. If I'm checking out 1 or 4 packages using mr.developer, I need to have just one config (instead of one for each package in your snippet). If, somehow, you need to change how the resources are compiled in the package itself, I don't need to replicate it either.

But thanks for the suggestion, I think it's a matter of taste.

**Comment by hvelarde** [comment]
can we close this issue now?

**Comment by idgserpro** [comment]
Not yet: I didn't close because I want to know if there's interest in adding a parameter to mr.developer that calls a script after a repository is checked out.

**Comment by mauritsvanrees** [comment]
I don't like it, especially if that command is to run buildout, even though this may seem reasonable. I fear situations like this:

- You run bin/develop checkout something.
- At the end this runs bin/buildout.
- A new version of zc.buildout or setuptools is found (probably because a version pin was updated and the user did not run bin/buildout yet).
- So buildout restarts itself.
- Now you have bin/develop which is running bin/buildout which is running bin/buildout. And in corner cases this may repeat itself.

It may all work fine, or it may all crash in weird ways.

I think the note that bin/develop prints after a checkout, reminding you to run bin/buildout in order for the checkout to have an effect, is enough.

**Comment by idgserpro** [comment]
> Now you have bin/develop which is running bin/buildout which is running bin/buildout.

![inception](https://user-images.githubusercontent.com/8203476/36902314-d32aba00-1e08-11e8-8083-78530e2bc081.gif)

Well, I think the approach of using plone.recipe.command above is enough. Thanks anyway.
