### ISSUE TITLE
Better error when the hg binary isn't available

### ISSUE THREAD

**Issue by rpatterson** [fschulze/mr.developer#66]
The current error is:

OSError: [Errno 2] No such file or directory

Which doesn't help the user to learn what they need to do.

**Comment by reinout** [comment]
Fixing this would mean an extra try...except in a number of places. That doesn't seem to be worth it.

A partial solution is to use python 3, funny enough. The error message there includes the offending file:

    FileNotFoundError: [Errno 2] No such file or directory: 'hg'

**Comment by fschulze** [comment]
In ``git.py`` we look up the executable first, which also makes it work on Windows: https://github.com/fschulze/mr.developer/blob/master/src/mr/developer/git.py#L29
